/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package praktikum1tugas;

import javax.swing.JOptionPane;

/**
 *
 * @author SUS
 */
public class NewJFrame extends javax.swing.JFrame {
    private boolean fnamaClicked = false;
    private boolean fnimClicked = false;
    private boolean falamatClicked = false;
    private boolean fnohpClicked = false;
    private boolean fprodiClicked = false;
    private boolean ffakultasClicked = false;
    private boolean falasanClicked = false;

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Nama = new javax.swing.JLabel();
        Nim = new javax.swing.JLabel();
        Alamat = new javax.swing.JLabel();
        nohp = new javax.swing.JLabel();
        Prodi = new javax.swing.JLabel();
        Fakultas = new javax.swing.JLabel();
        Jenis = new javax.swing.JLabel();
        fnama = new javax.swing.JTextField();
        falamat = new javax.swing.JTextField();
        fnohp = new javax.swing.JTextField();
        fprodi = new javax.swing.JTextField();
        ffakultas = new javax.swing.JComboBox<>();
        perempuan = new javax.swing.JRadioButton();
        lakilaki = new javax.swing.JRadioButton();
        smpn = new javax.swing.JButton();
        rst = new javax.swing.JButton();
        klr = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        falasan = new javax.swing.JTextArea();
        fnim = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(649, 478));

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));
        jPanel2.setMinimumSize(new java.awt.Dimension(0, 0));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(514, 98));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/praktikum1tugas/LOGO_UTM_DIKBUDRISTEK-removebg-preview.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("FORMULIR PENDAFTARAN UKM");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("UNIVERSITAS TRUNOJOYO MADURA");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Jl. Raya Telang, PO. Box. 2 Kamal, Bangkalan - Madura");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Telp : (031) 3011146, Fax. (031) 3011506");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Nama.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Nama.setText("NAMA LENGKAP                :");
        Nama.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NamaMouseClicked(evt);
            }
        });

        Nim.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Nim.setText("NIM                                        :");
        Nim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NimMouseClicked(evt);
            }
        });

        Alamat.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Alamat.setText("ALAMAT                              :");
        Alamat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AlamatMouseClicked(evt);
            }
        });

        nohp.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        nohp.setText("NO HP                                    :");
        nohp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nohpMouseClicked(evt);
            }
        });

        Prodi.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Prodi.setText("PRODI                                    :");
        Prodi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProdiMouseClicked(evt);
            }
        });

        Fakultas.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Fakultas.setText("FAKULTAS                           :");

        Jenis.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Jenis.setText("JENIS KELAMIN                  :");

        fnohp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnohpActionPerformed(evt);
            }
        });

        ffakultas.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        ffakultas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fakultas Teknik", "Fakultas Pertanian", "Fakultas Ekonomi dan Bisnis", "Fakultas Sosial Budaya", "Fakultas Keislaman", "Fakultas Pedidikan", "Fakultas Hukum" }));
        ffakultas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ffakultasMouseClicked(evt);
            }
        });
        ffakultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ffakultasActionPerformed(evt);
            }
        });

        buttonGroup1.add(perempuan);
        perempuan.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        perempuan.setText("Perempuan");

        buttonGroup1.add(lakilaki);
        lakilaki.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lakilaki.setText("Laki-Laki");
        lakilaki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lakilakiActionPerformed(evt);
            }
        });

        smpn.setText("SIMPAN");
        smpn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smpnActionPerformed(evt);
            }
        });

        rst.setText("RESET");
        rst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rstActionPerformed(evt);
            }
        });

        klr.setText("KELUAR");
        klr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                klrActionPerformed(evt);
            }
        });

        falasan.setColumns(20);
        falasan.setRows(5);
        falasan.setText("Tuliskan alasanmu disini\n");
        falasan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                falasanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(falasan);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 685, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(smpn)
                        .addGap(71, 71, 71)
                        .addComponent(rst)
                        .addGap(85, 85, 85)
                        .addComponent(klr))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Nama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Nim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Alamat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nohp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Prodi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Fakultas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Jenis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(fnama, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
                                    .addComponent(falamat)
                                    .addComponent(fnohp)
                                    .addComponent(fprodi)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(perempuan)
                                        .addGap(18, 18, 18)
                                        .addComponent(lakilaki))
                                    .addComponent(fnim)
                                    .addComponent(ffakultas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(8, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nama)
                    .addComponent(fnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nim)
                    .addComponent(fnim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Alamat)
                    .addComponent(falamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nohp)
                    .addComponent(fnohp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fprodi)
                    .addComponent(Prodi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Fakultas, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ffakultas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Jenis)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(perempuan)
                        .addComponent(lakilaki)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(smpn)
                    .addComponent(rst)
                    .addComponent(klr))
                .addGap(0, 24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fnohpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnohpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnohpActionPerformed

    private void ffakultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ffakultasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ffakultasActionPerformed

    private void lakilakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lakilakiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lakilakiActionPerformed

    private void smpnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smpnActionPerformed
        String Nama, Nim, Alamat, nohp, Prodi, Fakultas, Alasan, jns;
        Nama = fnama.getText();
        Nim = fnim.getText();
        Alamat = falamat.getText();
        nohp = fnohp.getText();
        Prodi = fprodi.getText();
        Fakultas =  (String) ffakultas.getSelectedItem();
        Alasan = falasan.getText();
        
        if(lakilaki.isSelected()){
            jns = "Laki-Laki";
        }
        else{
            jns = "Perempuan";
        }
        JOptionPane.showMessageDialog(null, "Nama: " + Nama  + "\n Nim: " + Nim 
                                                                  + "\n Alamat: " + Alamat 
                                                                  + "\n Nohp: " + nohp 
                                                                  + "\n Prodi: " + Prodi 
                                                                  + "\n Fakultas: " + Fakultas 
                                                                  + "\n Jenis Kelamin: " + jns 
                                                                  + "\n Alasan: " + Alasan );
    }//GEN-LAST:event_smpnActionPerformed

    private void rstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rstActionPerformed
        fnama.setText("");
        fnim.setText("");
        falamat.setText("");
        fnohp.setText("");
        fprodi.setText("");
        ffakultas.setSelectedIndex(0);
        falasan.setText("Tulis alasanmu disini");
        buttonGroup1.clearSelection();
    }//GEN-LAST:event_rstActionPerformed

    private void NamaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NamaMouseClicked
        if (!fnamaClicked){
            Nama.setText("");
            fnamaClicked = true;
        }
    }//GEN-LAST:event_NamaMouseClicked

    private void NimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NimMouseClicked
        if (!fnimClicked){
            Nim.setText("");
            fnimClicked = true;
        }
    }//GEN-LAST:event_NimMouseClicked

    private void AlamatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AlamatMouseClicked
        if (!falamatClicked){
            Alamat.setText("");
            falamatClicked = true;
        }
    }//GEN-LAST:event_AlamatMouseClicked

    private void nohpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nohpMouseClicked
        if (!fnohpClicked){
            nohp.setText("");
            fnohpClicked = true;
        }
    }//GEN-LAST:event_nohpMouseClicked

    private void ProdiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProdiMouseClicked
        if (!fprodiClicked){
            Prodi.setText("");
            fprodiClicked = true;
        }
    }//GEN-LAST:event_ProdiMouseClicked

    private void falasanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_falasanMouseClicked
        if (!falasanClicked){
            falasan.setText("");
            falasanClicked = true;
        }
    }//GEN-LAST:event_falasanMouseClicked

    private void ffakultasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ffakultasMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ffakultasMouseClicked

    private void klrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_klrActionPerformed
        System.exit(0);
    }//GEN-LAST:event_klrActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Alamat;
    private javax.swing.JLabel Fakultas;
    private javax.swing.JLabel Jenis;
    private javax.swing.JLabel Nama;
    private javax.swing.JLabel Nim;
    private javax.swing.JLabel Prodi;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField falamat;
    private javax.swing.JTextArea falasan;
    private javax.swing.JComboBox<String> ffakultas;
    private javax.swing.JTextField fnama;
    private javax.swing.JTextField fnim;
    private javax.swing.JTextField fnohp;
    private javax.swing.JTextField fprodi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton klr;
    private javax.swing.JRadioButton lakilaki;
    private javax.swing.JLabel nohp;
    private javax.swing.JRadioButton perempuan;
    private javax.swing.JButton rst;
    private javax.swing.JButton smpn;
    // End of variables declaration//GEN-END:variables
}
